### ISSUE TITLE
Cannot find Python error

### ISSUE THREAD

**Issue by robinren03** [cppmonkey/GNS3-Azure-SONiC#1]
Hi, I am new in GNS3, Ansible and SoNic (almost all related to this repo).

When I run
> ansible-playbook deploy-sonic-dc-topology.yml -vvv

I run into an error 
> TASK [Get the server facts] ************************************************************************************************
> fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: 1: /usr/bin/env python: not found\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}

I changed the script of `deploy-sonic-dc-topology.yml` to the following as directed by the issues on Ansible 
```
---
- hosts: localhost
  # Call the collections to use the respective modules
  collections:
    - davidban77.gns3
  vars:
    ansible_python_interpreter: "/root/miniconda3/bin/python"
    gns3_host: 192.168.1.34
    gns3_url: "http://{{ gns3_host }}"
```

However, I still face the same question of failing to find python. Could you please tell me what is happening? To my understanding, I only need one machine to run this script, as GNS3 should build a simulation (or emulation?) environment.
